#!/usr/bin/env bash
# Summary: Destroy a existing minike machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-name)"
fi

if [ -z "$KENV_MACHINE" ] || [ "$KENV_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

machine_stopped() {
  local machine="$1"
  local running="$(minikenv --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Stopped" ]
}

machine_running() {
  local machine="$1"
  local running="$(minikenv --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_destroy() {
  local machine="$1"
  minikenv delete \
      --profile ${machine} \
      2>&1
}

if machine_running "$KENV_MACHINE"; then
    if machine_destroy "$KENV_MACHINE"; then
        echo "kenv: destroy \`$KENV_MACHINE' destroyed" >&2
        exit 0
    else
        echo "kenv: destroy \`$KENV_MACHINE' not destroyed" >&2
        exit 1
    fi
elif machine_stopped "$KENV_MACHINE"; then
    if machine_destroy "$KENV_MACHINE"; then
        echo "kenv: destroy \`$KENV_MACHINE' destroyed" >&2
        exit 0
    else
        echo "kenv: destroy \`$KENV_MACHINE' not destroyed" >&2
        exit 1
    fi
else
    echo "kenv: destroy \`$KENV_MACHINE' does not exist" >&2
    exit 0
fi