#!/usr/bin/env bash
#
# Summary: Set or show the global kube machine
#
# Usage: kenv global <machine>
#        kenv global --unset
#

set -e
[ -n "$KENV_DEBUG" ] && set -x

# Provide kenv completions
if [ "$1" = "--complete" ]; then
  exec kenv-machines --bare
fi

KENV_MACHINE="$1"
KENV_MACHINE_FILE="${KENV_ROOT}/.kenv-machine"

if [ -n "$KENV_MACHINE" ]; then
  kenv-machine-file-write "$KENV_MACHINE_FILE" "$KENV_MACHINE"
  ln -svf "${KENV_ROOT}/machines/${KENV_MACHINE}/config" "${HOME}/.kube/config"
else
  kenv-machine-file-read "$KENV_MACHINE_FILE" ||
  { echo "kenv: no global machine configured"
    exit 1
  } >&2
fi

