#!/usr/bin/env bash
# Summary: Create a new multipass microk8s machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local query=".info[\"${1}\"][\"state\"]"
  local state="$(multipass info "${1}" --format json | jq --raw-output $query 2>&1)"
  [ "${state}" == "Running" ]
}

machine_stopped() {
  local query=".info[\"${1}\"][\"state\"]"
  local state="$(multipass info "${1}" --format json | jq --raw-output $query 2>&1)"
  [ "${state}" == "Stopped" ]
}

machine_create() {
  local machine="$1"
  multipass launch --name "${machine}" --mem 4G --disk 40G
  multipass exec "${machine}" -- sudo snap install microk8s --classic
  multipass exec "${machine}" -- sudo iptables -P FORWARD ACCEPT
  multipass exec "${machine}" -- sudo usermod -a -G microk8s ubuntu
}

if machine_running "${KENV_NAME}"; then
    echo "kenv: multipass create ${KENV_NAME} already running" >&2
    exit 0
elif machine_stopped "${KENV_NAME}"; then
    echo "kenv: multipass create ${KENV_NAME} already exists" >&2
    exit 0
else
    if machine_create "${KENV_NAME}"; then
        kenv-machine-file-write .kenv-machine multipass-"$KENV_NAME"
        multipass exec ${KENV_NAME} -- /snap/bin/microk8s.config > "${KENV_ROOT}/machines/multipass-${KENV_NAME}/config"
        echo "kenv: multipass create ${KENV_NAME} created" >&2
        exit 0
    else
        echo "kenv: multipass create ${KENV_NAME} not created" >&2
        exit 1
    fi
fi