#!/usr/bin/env bash
# Summary: Create a new kubernetes in docker

set -e
[ -n "$KENV_DEBUG" ] && set -x

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE_FILE="$(kenv-machine-file)"
  KENV_MACHINE="$(kenv-machine-file-read "$KENV_MACHINE_FILE" || true)"
fi

if [ -z "$KENV_MACHINE" ] || [ "$KENV_MACHINE" = "system" ]; then
  echo "no machine specified" >&2
  exit
fi

destroy_kind() {
  kind delete cluster --name "${1}"
  rm -rf "${KENV_ROOT}/machines/${KENV_MACHINE}"
}

if [ $KENV_TYPE == "kind" ]
then
  destroy_kind "${KENV_NAME}"
elif [ $KENV_TYPE == "minikube" ]
then
  echo "export KUBEMACHINE=\"${KENV_ROOT}/machines/${KENV_MACHINE}/machine\""
else
  echo "export KUBEMACHINE=\"${KENV_ROOT}/machines/default/machine\""
fi
