#!/usr/bin/env bash
# Summary: Create a new minikube machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-name)"
fi

if [ -z "$KENV_MACHINE" ] || [ "$KENV_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

export KUBECONFIG="${KENV_ROOT}/machines/minikube-${KENV_MACHINE}/config"

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_stopped() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Stopped" ]
}

machine_create() {
  local machine="$1"
  minikube start \
      --bootstrapper=kubeadm \
      --vm-driver=virtualbox \
      --memory 8192 \
      --cpus 4 \
      --profile ${machine} \
      2>&1
}

if machine_running "$KENV_MACHINE"; then
    echo "kenv: minikube create \`$KENV_MACHINE' already running" >&2
    exit 0
elif machine_stopped "$KENV_MACHINE"; then
    echo "kenv: minikube create \`$KENV_MACHINE' already exists" >&2
    exit 0
else
    if machine_create "$KENV_MACHINE"; then
        kenv-machine-file-write .kenv-machine minikube-"$KENV_MACHINE"
        echo "kenv: minikube create \`$KENV_MACHINE' created" >&2
        exit 0
    else
        echo "kenv: minikube create \`$KENV_MACHINE' not created" >&2
        exit 1
    fi
fi