#!/usr/bin/env bash
# Summary: Create a new minikube machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_stopped() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Stopped" ]
}

machine_start() {
  local machine="$1"
  minikube profile $machine >&2
  minikube --profile "$machine" start >&2
}

if machine_running "$KENV_NAME"; then
    echo "kenv: minikube activate $KENV_NAME already running" >&2
    echo "$(minikube --profile ${KENV_NAME} docker-env)"
    exit 0
elif machine_stopped "$KENV_NAME"; then
    if machine_start "$KENV_NAME"; then
        echo "kenv: minikube activate $KENV_NAME started" >&2
        echo "$(minikube --profile ${KENV_NAME} docker-env)"
        exit 0
    else
        echo "kenv: minikube activate ${KENV_NAME} not started" >&2
        exit 1
    fi
fi