#!/usr/bin/env bash
# Summary: Create a new kubernetes in docker

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

KENV_TYPE="$(kenv-machine-type ${KENV_MACHINE})"
KENV_NAME="$(kenv-machine-name ${KENV_MACHINE})"

destroy_kind() {
  kind delete cluster --name "${1}"
  rm -rf "${KENV_ROOT}/machines/${KENV_MACHINE}"
}

if [ $KENV_TYPE == "kind" ]
then
  echo "kenv: kind destroy ${KENV_NAME}" >&2
  destroy_kind "${KENV_NAME}"
elif [ $KENV_TYPE == "minikube" ]
then
  echo "kenv: minikube destroy ${KENV_NAME}" >&2
elif [ $KENV_TYPE == "multipass" ]
then
  echo "kenv: multipass destroy ${KENV_NAME}" >&2
fi

  echo "export KUBEMACHINE=\"${KENV_ROOT}/machines/default/machine\""
