#!/usr/bin/env bash
# Usage: kenv config-file-read <file>

set -e
[ -n "$KENV_DEBUG" ] && set -x

CONFIG_FILE="$1"

if [ -e "$CONFIG_FILE" ]; then
  # Read the first non-whitespace word from the specified config file.
  # Be careful not to load it whole in case there's something crazy in it.
  config=""
  while read -a words; do
    word="${words[0]}"
    if [ -z "$config" ] && [ -n "$word" ]; then
      config="$word"
    fi
  done < <( cat "$CONFIG_FILE" && echo )

  if [ -n "$config" ]; then
    echo "$config"
    exit
  fi
fi

exit 1
