#!/usr/bin/env bash
# Summary: Create a new kind machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "$KENV_NAME" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

if [ -z "$KENV_NAME" ]; then
  echo "no machine specified"
  exit
fi

machine_running() {
  [[ "$(docker container ls --format='{{json .Names}}' | jq)" =~ ${1}-control-plane ]]
}

machine_start() {
#  kind create cluster --name "${1}"
  echo "kenv: kind start '${KENV_NAME}'" >&2
}

if machine_running "$KENV_NAME"; then
#    echo "kenv: kind create \`$KENV_NAME' already running" >&2
    exit 0
else
    if machine_start "$KENV_NAME"; then
      echo "export DOCKER_TLS_VERIFY="
      echo "export DOCKER_HOST="
      echo "export DOCKER_CERT_PATH="
#        kenv-machine-file-write .kenv-machine kind-"$KENV_NAME"
#        mkdir "${KENV_ROOT}/machines/kind-${1}"
#        cp "${HOME}/.kube/kind-config-${1}" "${KENV_ROOT}/machines/kind-${1}/config"
#        echo "kenv: kind create \`$KENV_NAME' created" >&2
        exit 0
    else
#        echo "kenv: kind create \`$KENV_NAME' not created" >&2
        exit 1
    fi
fi