#!/usr/bin/env bash
# Summary: Display the version of kenv
#
# Displays the version number of this kenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$KENV_DEBUG" ] && set -x

VERSION="0.0.0"

cd "$KENV_ROOT"
git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
git_revision="${git_revision#v}"

echo "kenv ${git_revision:-$VERSION}"
