#!/usr/bin/env bash
# Summary: Create a new minikenv machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

if [ -z "$KENV_MACHINE" ]
then
  echo "no machine specified"
  exit
fi

echo "export KUBECONFIG=\"${KENV_ROOT}/machines/${KENV_MACHINE}/config\""


