#!/usr/bin/env bash
# Summary: Show the current kube machine name

set -e
[ -n "$KENV_DEBUG" ] && set -x

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE_FILE="$(kenv-machine-file)"
  KENV_MACHINE="$(kenv-machine-file-read "$KENV_MACHINE_FILE" || true)"
fi

machine_exists() {
  [ -d "${KENV_ROOT}/machines/${1}" ]
}

if machine_exists "$KENV_MACHINE"; then
  echo "$KENV_MACHINE"
else
  echo "kenv: machine \`$KENV_MACHINE' is not installed" >&2
  exit 1
fi
