#!/usr/bin/env bash
# Summary: Save a new kubernetes in docker

set -e
[ -n "$KENV_DEBUG" ] && set -x

unset KUBECONFIG

KENV_TYPE="$1"
KENV_NAME="$2"

if [ -z "$KENV_TYPE" ] && [ -z "$KENV_NAME" ]; then
  KENV_TYPE="$(kenv-machine-type)"
  KENV_NAME="$(kenv-machine-name)"
fi

if [ ! -d "${KENV_ROOT}/machines/${KENV_TYPE}-${KENV_NAME}" ]
then
  mkdir "${KENV_ROOT}/machines/${KENV_TYPE}-${KENV_NAME}"
fi

if [ $KENV_TYPE == "kind" ]
then
  echo "kenv: kind create ${KENV_NAME}" >&2
  kenv-kind-create "${KENV_NAME}"
elif [ $KENV_TYPE == "minikube" ]
then
  echo "kenv: minikube create ${KENV_NAME}" >&2
  kenv-minikube-create "${KENV_NAME}"
elif [ $KENV_TYPE == "microk8s" ]
then
  echo "kenv: microk8s create ${KENV_NAME}" >&2
  kenv-microk8s-create "${KENV_NAME}"
elif [ $KENV_TYPE == "k3s" ]
then
  echo "kenv: k3s create ${KENV_NAME}" >&2
  kenv-k3s-create "${KENV_NAME}"
elif [ $KENV_TYPE == "remote" ]
then
  echo "kenv: remote create" >&2
  kenv-remote-create "${KENV_NAME}"
else
  { echo "kenv: unknown type"
    exit 1
  } >&2
fi
