#!/usr/bin/env bash
#
# Summary: Set or show the global kube config
#
# Usage: kenv global <config>
#        kenv global --unset
#

set -e
[ -n "$KENV_DEBUG" ] && set -x

# Provide kenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec kenv-configs --bare
fi

KENV_CONFIG="$1"
KENV_CONFIG_FILE="${JKENV_ROOT}/config"

if [ -n "$KENV_CONFIG" ]; then
  kenv-config-file-write "$KENV_CONFIG_FILE" "$KENV_CONFIG"
  ln -s ""
else
  kenv-config-file-read "$KENV_CONFIG_FILE" ||
  kenv-config-file-read "${KENV_ROOT}/global" ||
  kenv-config-file-read "${KENV_ROOT}/default" ||
  echo system
fi

