#!/usr/bin/env bash
#
# Summary: Set or show the local directory specific kube machine
#
# Usage: kenv local <version>
#        kenv local --unset
#
# Sets the local directory specific kube machine by writing the
# version name to a file named `.kenv-machine'.
#

set -e
[ -n "$KENV_DEBUG" ] && set -x

# Provide kenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  exec kenv-machines --bare
fi

KENV_MACHINE="$1"

if [ "$KENV_MACHINE" = "--unset" ]; then
  rm -f .kenv-machine
elif [ -n "$KENV_MACHINE" ]; then
  kenv-machine-file-write .kenv-machine "$KENV_MACHINE"
else
  kenv-machine-file-read .kenv-machine ||
  { echo "kenv: no local machine configured for this directory"
    exit 1
  } >&2
fi
