#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific kube machine
#
# Usage: kenv shell <machine>
#        kenv shell --unset
#
# Sets a shell-specific minikenv machine by setting the `KENV_MACHINE'
# environment variable in your shell. This machine overrides local
# application-specific machines and the global macine.
#
# <machine> should be a string matching an installed minikenv machine known to kenv.
# The special machine string `system' will use your default machine.
# Run `kenv machine' for a list of available Node machines.

set -e
[ -n "$KENV_DEBUG" ] && set -x

# Provide kenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec kenv-machines --bare
fi

machine="$1"

if [ -z "$machine" ]; then
  if [ -z "$KENV_MACHINE" ]; then
    echo "kenv: no shell-specific machine configured" >&2
    exit 1
  else
    echo "echo \"\$KENV_MACHINE\""
    exit
  fi
fi

if [ "$machine" = "--unset" ]; then
  echo "unset KENV_MACHINE"
  exit
fi

# Make sure the specified machine is installed.
if kenv-prefix "$machine" >/dev/null; then
  echo "export KENV_MACHINE=\"${machine}\""
else
  echo "return 1"
  exit 1
fi
