#!/usr/bin/env bash

set -e
[ -n "$KENV_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${KENV_ROOT}" ]; then
  KENV_ROOT="${HOME}/.kenv"
else
  KENV_ROOT="${KENV_ROOT%/}"
fi
export KENV_ROOT

if [ -z "${KENV_DIR}" ]; then
  KENV_DIR="$(pwd)"
else
  cd "$KENV_DIR" 2>/dev/null || {
    echo "kenv: cannot change working directory to \`$KENV_DIR'"
    exit 1
  } >&2
  KENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export KENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${KENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${KENV_HOOK_PATH}:${KENV_ROOT}/kenv.d:/usr/local/etc/kenv.d:/etc/kenv.d:/usr/lib/kenv/hooks"
for plugin_hook in "${KENV_ROOT}/plugins/"*/etc/kenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export KENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(kenv---version)\n$(kenv-help)" >&2
  ;;
"-v" )
  exec kenv---version
  ;;
* )
  command_path="$(command -v "kenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "kenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
