#!/usr/bin/env bash
# Summary: Machineure the shell environment for kenv
# Usage: eval "$(kenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$KENV_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
		shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load kenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo 'eval "$(kenv init -)"'
    echo
  } >&2

  exit 1
fi

if [ ! -d "${KENV_ROOT}/machines" ]
then
  mkdir -p "${KENV_ROOT}/machines/original"
fi

if [ ! -d "${KENV_ROOT}/machines/original" ]
then
  mkdir -p "${KENV_ROOT}/machines/original"
  if [ -d "$HOME/.kube" ] && [ -f "$HOME/.kube/config" ]
  then
    cp ~/.kube/config "${KENV_ROOT}"/machines/original/config
    echo "original" > "${KENV_ROOT}/.kenv-machine"
  fi
fi

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/kenv.${shell}\""
  ;;
esac

if [ -z "$no_rehash" ]; then
  echo 'kenv rehash 2>/dev/null'
fi

commands=(`kenv-commands --sh`)
IFS="|"
cat <<EOS
kenv() {
  typeset command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`kenv "sh-\$command" "\$@"\`;;
  *)
    command kenv "\$command" "\$@";;
  esac
}
EOS
