#!/usr/bin/env bash
# Summary: Destroy the minikube

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_stop() {
  local machine="$1"
  minikube --profile ${machine} stop
}

machine_delete() {
  local machine="$1"
  minikube --profile ${machine} delete
}

if machine_running "$KENV_NAME"; then
    echo "kenv: machine $KENV_NAME stop" >&2
    machine_stop "$KENV_NAME" && \
      machine_delete "$KENV_NAME"
    exit 0
else
    echo "kenv: machine $KENV_NAME is not running" >&2
    machine_delete "$KENV_NAME"
    exit 0
fi