#!/usr/bin/env bash
# Summary: Create a new kind machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  [[ "$(docker container ls --format='{{json .Names}}' | jq)" =~ ${1}-control-plane ]]
}

machine_create() {
  kind create cluster --name "${1}" >&2
}

if machine_running "KENV_NAME"; then
    echo "kenv: kind create \`$KENV_NAME' already running" >&2
    exit 0
else
    if machine_create "$KENV_NAME"; then
        kenv-machine-file-write .kenv-machine kind-"$KENV_NAME"
        mv "${HOME}/.kube/kind-config-${1}" "${KENV_ROOT}/machines/kind-${NAME}/config"
        echo "kenv: kind create \`$KENV_NAME' created" >&2
        exit 0
    else
        echo "kenv: kind create \`$KENV_NAME' not created" >&2
        exit 1
    fi
fi