#!/usr/bin/env bash
# Summary: Create a new multipass k3s machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi


machine_create() {
  local machine="$1"
}

if machine_create "${KENV_NAME}"; then
    kenv-machine-file-write .kenv-machine remote-"$KENV_NAME"
    echo "kenv: remote create ${KENV_NAME} created" >&2
    exit 0
else
    echo "kenv: remote create ${KENV_NAME} not created" >&2
    exit 1
fi
