#!/usr/bin/env bash
# Summary: Start the minikube dashboard

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_start_dashboard() {
  local machine="$1"
  minikube --profile ${machine} dashboard
}

if machine_running "$KENV_NAME"; then
    echo "kenv: machine $KENV_NAME start dashboard" >&2
    machine_start_dashboard "$KENV_NAME" &
    exit 0
else
    echo "kenv: machine $KENV_NAME is not running" >&2
    exit 1
fi