#!/usr/bin/env bash
# Summary: Create a new minikenv machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

KENV_TYPE="$(kenv-machine-type ${KENV_MACHINE})"
KENV_NAME="$(kenv-machine-name ${KENV_MACHINE})"

if [ $KENV_TYPE == "kind" ]
then
  echo "kenv: kind dashboard ${KENV_NAME}" >&2
elif [ $KENV_TYPE == "minikube" ]
then
  echo "kenv: minikube dashboard ${KENV_NAME}" >&2
  kenv-minikube-dashboard "${KENV_NAME}"
elif [ $KENV_TYPE == "multipass" ]
then
  echo "kenv: multipass dashboard ${KENV_NAME}" >&2
  kenv-multipass-dashboard "${KENV_NAME}"
elif [ $KENV_TYPE == "remote" ]
then
  echo "kenv: remote dashboard ${KENV_NAME}" >&2
else
  { echo "kenv: unknown type"
    exit 1
  } >&2
fi

echo "export KUBECONFIG=\"${KENV_ROOT}/machines/${KENV_MACHINE}/config\""


