#!/usr/bin/env bash
# Summary: Create a new minikenv config

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_CONFIG="$1"

if [ -z "$KENV_CONFIG" ]; then
  KENV_CONFIG="$(kenv-config-name)"
fi

if [ -z "$KENV_CONFIG" ] || [ "$KENV_CONFIG" = "system" ]; then
  echo "no config specified"
  exit
fi

#IFS='-' read -ra MY_ARRAY <<< "$KENV_CONFIG"
#KENV_TYPE="${MY_ARRAY[0]}"
#KENV_NAME="${MY_ARRAY[1]}"
#
#if [ $KENV_TYPE == "kind" ]
#then
#  echo "export KUBECONFIG=\"${KENV_ROOT}/configs/${KENV_CONFIG}/config\""
#elif [ $KENV_TYPE == "minikube" ]
#then
#  echo "export KUBECONFIG=\"${KENV_ROOT}/configs/${KENV_CONFIG}/config\""
#else
#  echo "export KUBECONFIG=\"${KENV_ROOT}/configs/${KENV_CONFIG}/config\""
#fi

echo "export KUBECONFIG=\"${KENV_ROOT}/configs/${KENV_CONFIG}/config\""


