#!/usr/bin/env bash
# Usage: kenv completions <command> [arg1 arg2...]

set -e
[ -n "$KENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  kenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "kenv-$COMMAND" || command -v "kenv-sh-$COMMAND")"
if grep -i "^# provide kenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
