#!/usr/bin/env bash
# Summary: Activate a multipass machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local query=".info[\"${1}\"][\"state\"]"
  local state="$(multipass info "${1}" --format json | jq --raw-output $query 2>&1)"
  [ "${state}" == "Running" ]
}

machine_stopped() {
  local query=".info[\"${1}\"][\"state\"]"
  local state="$(multipass info "${1}" --format json | jq --raw-output $query 2>&1)"
  [ "${state}" == "Stopped" ]
}

machine_start() {
  local machine="$1"
  multipass start $machine
}

if machine_running "${KENV_NAME}"; then
    echo "kenv: multipass activate ${KENV_NAME} already running" >&2
    exit 0
elif machine_stopped "${KENV_NAME}"; then
    if machine_start "${KENV_NAME}"; then
        echo "kenv: multipass activate ${KENV_NAME} started" >&2
        exit 0
    else
        echo "kenv: multipass activate ${KENV_NAME} not started" >&2
        exit 1
    fi
fi