#!/usr/bin/env bash
# Summary: Show the current kube machine name

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="${1}"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE_FILE="$(kenv-machine-file)"
  KENV_MACHINE="$(kenv-machine-file-read "$KENV_MACHINE_FILE" || true)"
fi

IFS='-' read -ra MY_ARRAY <<< "$KENV_MACHINE"
echo "${MY_ARRAY[0]}"

