#!/usr/bin/env bash
# Summary: Activate an existing k3s machine in docker

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local machine="$1"
  local state=$(k3d cluster list -o json | jq --arg machine "${machine}" --raw-output '.[] | select(.name == $machine) | .nodes[] | select(.role == "server") | .State.Status')
  [ "${state}" == "running" ]
}

machine_stopped() {
  local machine="$1"
  local state=$(k3d cluster list -o json | jq --arg machine "${machine}" --raw-output '.[] | select(.name == $machine) | .nodes[] | select(.role == "server") | .State.Status')
  [ "${state}" == "exited" ]
}

machine_start() {
  local machine="$1"
  k3d cluster start ${machine} >&2
}

if machine_running "$KENV_NAME"; then
    echo "kenv: k3d activate $KENV_NAME already running" >&2
    exit 0
elif machine_stopped "$KENV_NAME"; then
    if machine_start "$KENV_NAME"; then
        echo "kenv: k3d activate ${KENV_NAME} started" >&2
        echo "export DOCKER_TLS_VERIFY="
        echo "export DOCKER_HOST="
        echo "export DOCKER_CERT_PATH="
        exit 0
    else
        echo "kenv: k3d activate ${KENV_NAME} not started" >&2
        exit 1
    fi
fi
