#!/usr/bin/env bash
# Summary: Create a new minikube machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

if [ -z "$KENV_MACHINE" ] || [ "$KENV_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_stopped() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Stopped" ]
}

machine_start() {
  local machine="$1"
  minikube profile $machine >&2
  minikube --profile "$machine" start >&2
}

if machine_running "$KENV_MACHINE"; then
    echo "kenv: minikube activate \`$KENV_MACHINE' already running" >&2
    echo "$(minikube --profile ${KENV_MACHINE} docker-env)"
    exit 0
elif machine_stopped "$KENV_MACHINE"; then
    if machine_start "$KENV_MACHINE"; then
        echo "kenv: minikube activate \`$KENV_MACHINE' started" >&2
        echo "$(minikube --profile ${KENV_MACHINE} docker-env)"
        exit 0
    else
        echo "kenv: minikube activate ${KENV_MACHINE} not started" >&2
        exit 1
    fi
fi