#!/usr/bin/env bash
# Summary: Create a new minikenv machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

KENV_TYPE="$(kenv-machine-type ${KENV_MACHINE})"
KENV_NAME="$(kenv-machine-name ${KENV_MACHINE})"

if [ $KENV_TYPE == "kind" ]
then
  echo "kenv: kind activate ${KENV_NAME}" >&2
  kenv-kind-activate "${KENV_NAME}"
elif [ $KENV_TYPE == "minikube" ]
then
  echo "kenv: minikube activate ${KENV_NAME}" >&2
  kenv-minikube-activate "${KENV_NAME}"
elif [ $KENV_TYPE == "microk8s" ]
then
  echo "kenv: microk8s activate ${KENV_NAME}" >&2
  kenv-microk8s-activate "${KENV_NAME}"
elif [ $KENV_TYPE == "k3s" ]
then
  echo "kenv: k3s activate ${KENV_NAME}" >&2
  kenv-k3s-activate "${KENV_NAME}"
elif [ $KENV_TYPE == "k3d" ]
then
  echo "kenv: k3d activate ${KENV_NAME}" >&2
  kenv-k3d-activate "${KENV_NAME}"
elif [ $KENV_TYPE == "remote" ]
then
  echo "kenv: remote activate ${KENV_NAME}" >&2
else
  { echo "kenv: unknown type"
    exit 1
  } >&2
fi

echo "export KUBECONFIG=\"${KENV_ROOT}/machines/${KENV_MACHINE}/config\""


