#!/usr/bin/env bash
# Summary: Create a new k3s machine in docker

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local machine="$1"
  local state=$(k3d cluster list -o json | jq --arg machine "${machine}" --raw-output '.[] | select(.name == $machine) | .nodes[] | select(.role == "server") | .State.Status')
  [ "${state}" == "running" ]
}

machine_stopped() {
  local machine="$1"
  local state=$(k3d cluster list -o json | jq --arg machine "${machine}" --raw-output '.[] | select(.name == $machine) | .nodes[] | select(.role == "server") | .State.Status')
  [ "${state}" == "exited" ]
}

machine_create() {
  local machine="$1"
  k3d cluster create ${machine} --registry-create k3d-${machine}-registry
}

if machine_running "${KENV_NAME}"; then
    echo "kenv: k3d create ${KENV_NAME} already running" >&2
    exit 0
elif machine_stopped "${KENV_NAME}"; then
    echo "kenv: k3d create ${KENV_NAME} already exists" >&2
    exit 0
else
    if machine_create "${KENV_NAME}"; then
        kenv-machine-file-write .kenv-machine k3d-"$KENV_NAME"
        mv "${HOME}/.kube/config" "${KENV_ROOT}/machines/k3d-${KENV_NAME}/config"
        echo "kenv: k3d create ${KENV_NAME} created" >&2
        exit 0
    else
        echo "kenv: k3d create ${KENV_NAME} not created" >&2
        exit 1
    fi
fi
