#!/usr/bin/env bash
# Summary: Show the current kube machine and its origin
#
# Shows the currently selected minikenv machine and how it was
# selected. To obtain only the version string, use `kenv machine-name'.

set -e
[ -n "$KENV_DEBUG" ] && set -x

echo "$(kenv-machine-desc) (set by $(kenv-machine-origin))" >&2
