#!/usr/bin/env bash
# Summary: Create a new kind machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  [[ "$(docker container ls --format='{{json .Names}}' | jq)" =~ ${1}-control-plane ]]
}

machine_delete() {
  kind delete cluster --name "${1}"
}

if machine_running "$KENV_NAME"; then
    echo "kenv: machine $KENV_NAME stop" >&2
    machine_stop "$KENV_NAME" && \
      machine_delete "$KENV_NAME"
    exit 0
else
    echo "kenv: machine $KENV_NAME is not running" >&2
    machine_delete "$KENV_NAME"
    exit 0
fi
