#!/usr/bin/env bash
# Summary: Create a new kubernetes in docker

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

KENV_TYPE="$(kenv-machine-type ${KENV_MACHINE})"
KENV_NAME="$(kenv-machine-name ${KENV_MACHINE})"


case "${KENV_TYPE}" in
kind)
  echo "kenv: kind destroy ${KENV_NAME}" >&2
  kenv-kind-destroy "${KENV_NAME}"
  ;;
minikube)
  echo "kenv: minikube destroy ${KENV_NAME}" >&2
  kenv-minikube-destroy "${KENV_NAME}"
  ;;
k3d)
  echo "kenv: k3d destroy ${KENV_NAME}" >&2
  kenv-k3d-destroy "${KENV_NAME}"
  ;;
microk8s)
  echo "kenv: microk8s destroy ${KENV_NAME}" >&2
  kenv-microk8s-destroy "${KENV_NAME}"
  ;;
*)
  echo "kenv: incorrect type ${KENV_NAME}" >&2
  ;;
esac

rm -rf "${KENV_ROOT}/machines/${KENV_MACHINE}"

#echo "export KUBEMACHINE=\"${KENV_ROOT}/machines/default/machine\""
