#!/usr/bin/env bash
# Summary: Detect the file that sets the current kenv machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

find_local_machine_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.kenv-machine" ]; then
      echo "${root}/.kenv-machine"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_machine_file "$KENV_DIR"
[ "$KENV_DIR" = "$PWD" ] || find_local_machine_file "$PWD"

GLOBAL_MACHINE_FILE="${KENV_ROOT}/.kenv-machine"

if [ -e "$GLOBAL_MACHINE_FILE" ]; then
  echo "$GLOBAL_MACHINE_FILE"
elif [ -e "${KENV_ROOT}/global" ]; then
  echo "${KENV_ROOT}/global"
elif [ -e "${KENV_ROOT}/default" ]; then
  echo "${KENV_ROOT}/default"
else
  echo "$GLOBAL_MACHINE_FILE"
fi
