#!/usr/bin/env bash
# Usage: kenv config-file-write <file> <config>

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_CONFIG_FILE="$1"
KENV_CONFIG="$2"

if [ -z "$KENV_CONFIG" ] || [ -z "$KENV_CONFIG_FILE" ]; then
  kenv-help --usage config-file-write >&2
  exit 1
fi

# Make sure the specified config is installed.
#kenv-prefix "$KENV_CONFIG" >/dev/null

# Write the config out to disk.
echo "$KENV_CONFIG" > "$KENV_CONFIG_FILE"
