#!/usr/bin/env bash
# Summary: Display prefix for a kenv machine
# Usage: kenv prefix [<machine>]
#
# Displays the directory where a kenv machine is installed.

set -e
[ -n "$KENV_DEBUG" ] && set -x

# Provide kenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec kenv-machines --bare
fi

if [ -n "$1" ]; then
  export KENV_MACHINE="$1"
elif [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

KENV_PREFIX_PATH="${KENV_ROOT}/machines/${KENV_MACHINE}"
if [ ! -d "$KENV_PREFIX_PATH" ]; then
  echo "kenv: machine \`${KENV_MACHINE}' not installed" >&2
  exit 1
fi

echo "$KENV_PREFIX_PATH"
