#!/usr/bin/env bash
# Summary: List all kube configs available to kenv
# Usage: kenv configs
#
# Lists all kube configs found in `$KENV_ROOT/configs/*'.

set -e
[ -n "$KENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  inst_prefix=""
  miss_prefix=""
  current_config=""
  include_system=""
else
  hit_prefix="* "
  inst_prefix="+ "
  miss_prefix="  "
  current_config="$(kenv-config-name || true)"
  include_system="1"
fi

print_config() {
  if [ "$1" == "$current_config" ]; then
    echo "${hit_prefix}${inst_prefix}$(kenv-config 2>/dev/null) $1"
  elif [[ -d  "${KENV_ROOT}/configs/$1" ]]; then
    echo "${miss_prefix}${inst_prefix}$1"
  else
    echo "${miss_prefix}${miss_prefix}$1"
  fi
}

if [ -n "$include_system" ]; then
  print_config system
fi

for path in "${KENV_ROOT}/configs"/*; do
  if [ -d "$path" ]; then
    print_config "${path##*/}"
  fi
done
