#!/usr/bin/env bash
# Summary: Create a new kubernetes in docker

set -e
[ -n "$KENV_DEBUG" ] && set -x

unset KUBECONFIG

KENV_TYPE="$1"
KENV_NAME="$2"

if [ -z "$KENV_TYPE" ] || [ -z "$KENV_NAME" ]; then
  KENV_TYPE="$(kenv-machine-type)"
  KENV_NAME="$(kenv-machine-name)"
fi

if [ ! -d "${KENV_ROOT}/machines/${KENV_TYPE}-${KENV_NAME}" ]
then
  mkdir "${KENV_ROOT}/machines/${KENV_TYPE}-${KENV_NAME}"
  if [ -d "$HOME/.kube" ] && [ -f "$HOME/.kube/config" ]
  then
    cp ~/.kube/config "${KENV_ROOT}/machines/${KENV_TYPE}-${KENV_NAME}/config"
    echo "${KENV_TYPE}-${KENV_NAME}" > ".kenv-machine"
  fi
fi
