#!/usr/bin/env bash
#
# Summary: Set or show the local directory specific kube config
#
# Usage: kenv local <version>
#        kenv local --unset
#
# Sets the local application-specific minikenv config by writing the
# version name to a file named `.kenv-config'.
#

set -e
[ -n "$KENV_DEBUG" ] && set -x

# Provide kenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec kenv-configs --bare
fi

KENV_CONFIG="$1"

if [ "$KENV_CONFIG" = "--unset" ]; then
  rm -f .kenv-config
elif [ -n "$KENV_CONFIG" ]; then
  kenv-config-file-write .kenv-config "$KENV_CONFIG"
else
  kenv-config-file-read .kenv-config ||
  { echo "kenv: no local config configured for this directory"
    exit 1
  } >&2
fi
