#!/usr/bin/env bash
# Summary: Create a new minikube machine

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

MEM="${2:-8g}"
DSK="${3:-50g}"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_stopped() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Stopped" ]
}

machine_create() {
  local machine="$1"
  local memory="$2"
  local disksize="$3"
#      --kubernetes-version=v1.17.0 \
#      --vm-driver=virtualbox \
  minikube start \
      --bootstrapper=kubeadm \
      --vm-driver=docker \
      --memory ${memory} \
      --disk-size ${disksize} \
      --cpus 4 \
      --addons=dashboard \
      --addons=ingress \
      --addons=metrics-server \
      --addons=registry \
      --profile ${machine} \
      2>&1
}

if machine_running "$KENV_NAME"; then
    echo "kenv: minikube create ${KENV_NAME} already running" >&2
    exit 0
elif machine_stopped "$KENV_NAME"; then
    echo "kenv: minikube create ${KENV_NAME} already exists" >&2
    exit 0
else
    if machine_create "$KENV_NAME" "${MEM}" "${DSK}"; then
        kenv-machine-file-write .kenv-machine minikube-"$KENV_NAME"
        mv "${HOME}/.kube/config" "${KENV_ROOT}/machines/minikube-${KENV_NAME}/config"
        echo "kenv: minikube create ${KENV_NAME} created" >&2
        exit 0
    else
        echo "kenv: minikube create ${KENV_NAME} not created" >&2
        exit 1
    fi
fi
