#!/usr/bin/env bash
# Summary: Start the multipass microk8s dashboard

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_NAME="$1"

if [ -z "${KENV_NAME}" ]; then
  KENV_NAME="$(kenv-machine-name)"
fi

machine_running() {
  local query=".info[\"${1}\"][\"state\"]"
  local state="$(multipass info "${1}" --format json | jq --raw-output $query 2>&1)"
  [ "${state}" == "Running" ]
}

machine_start_dashboard() {
  local machine="$1"
  multipass exec ${machine} -- /snap/bin/microk8s.enable dns dashboard
}

if machine_running "$KENV_NAME"; then
    echo "kenv: multipass machine $KENV_NAME start dashboard" >&2
    machine_start_dashboard "$KENV_NAME" &
    exit 0
else
    echo "kenv: multipass machine $KENV_NAME is not running" >&2
    exit 1
fi