#!/usr/bin/env bash
# Summary: proxy a new kubernetes

set -e
[ -n "$KENV_DEBUG" ] && set -x

KENV_MACHINE="$1"

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-desc)"
fi

KENV_TYPE="$(kenv-machine-type ${KENV_MACHINE})"
KENV_NAME="$(kenv-machine-name ${KENV_MACHINE})"

if [ $KENV_TYPE == "kind" ]
then
  echo "kenv: kind proxy ${KENV_NAME}" >&2
elif [ $KENV_TYPE == "minikube" ]
then
  echo "kenv: minikube proxy ${KENV_NAME}" >&2
elif [ $KENV_TYPE == "multipass" ]
then
  echo "kenv: multipass proxy ${KENV_NAME}" >&2
elif [ $KENV_TYPE == "remote" ]
then
  echo "kenv: remote proxy ${KENV_NAME}" >&2
else
  { echo "kenv: unknown type"
    exit 1
  } >&2
fi

kubectl proxy


