#!/usr/bin/env bash
# Summary: Start the minikube dashboard

set -e
[ -n "$KENV_DEBUG" ] && set -x

if [ -z "$KENV_MACHINE" ]; then
  KENV_MACHINE="$(kenv-machine-name)"
fi

if [ -z "$KENV_MACHINE" ] || [ "$KENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_start_dashboard() {
  local machine="$1"
  minikube --profile ${machine} dashboard
}

if machine_running "$KENV_MACHINE"; then
    echo "kenv: machine \`$KENV_MACHINE' start dashboard" >&2
    machine_start_dashboard "$KENV_MACHINE" &
    exit 0
else
    echo "kenv: machine \`$KENV_MACHINE' is not running" >&2
    exit 1
fi