#!/usr/bin/env bash
# Summary: Explain how the current minikenv config is set

set -e
[ -n "$KENV_DEBUG" ] && set -x

if [ -n "$KENV_CONFIG" ]; then
  echo "KENV_CONFIG environment variable"
else
  kenv-config-file
fi
