#!/usr/bin/env bash
# Summary: Show the current kube config and its origin
#
# Shows the currently selected minikenv config and how it was
# selected. To obtain only the version string, use `kenv config-name'.

set -e
[ -n "$KENV_DEBUG" ] && set -x

echo "$(kenv-config-name) (set by $(kenv-config-origin))"
