#!/usr/bin/env bash
# Usage: kube completions <command> [arg1 arg2...]

set -e
[ -n "$KUBE_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  kube-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "kube-$COMMAND" || command -v "kube-sh-$COMMAND")"
if grep -i "^# provide kube completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
