#!/usr/bin/env bash
# Summary: Start the minikube dashboard

set -e
[ -n "$KUBE_DEBUG" ] && set -x

if [ -z "$KUBE_MACHINE" ]; then
  KUBE_MACHINE="$(kube-machine-name)"
fi

if [ -z "$KUBE_MACHINE" ] || [ "$KUBE_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.MinikubeStatus}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_start_dashboard() {
  local machine="$1"
  minikube --profile ${machine} dashboard
}

if machine_running "$KUBE_MACHINE"; then
    machine_start_dashboard "$KUBE_MACHINE" &
    echo "kube: machine \`$KUBE_MACHINE' already running" >&2
    exit 0
else
    echo "kube: machine \`$KUBE_MACHINE' is not running" >&2
    exit 1
fi