#!/usr/bin/env bash
# Summary: Explain how the current minikube machine is set

set -e
[ -n "$KUBE_DEBUG" ] && set -x

if [ -n "$KUBE_MACHINE" ]; then
  echo "KUBE_MACHINE environment variable"
else
  kube-machine-file
fi
