#!/usr/bin/env bash
# Summary: Display the version of kube
#
# Displays the version number of this kube release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$KUBE_DEBUG" ] && set -x

VERSION="0.0.0"

cd "$KUBE_ROOT"
git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
git_revision="${git_revision#v}"

echo "kube ${git_revision:-$VERSION}"
