#!/usr/bin/env bash
# Summary: Show the current minikube machine

set -e
[ -n "$KUBE_DEBUG" ] && set -x

if [ -z "$KUBE_MACHINE" ]; then
  KUBE_MACHINE_FILE="$(kube-machine-file)"
  KUBE_MACHINE="$(kube-machine-file-read "$KUBE_MACHINE_FILE" || true)"
fi

if [ -z "$KUBE_MACHINE" ] || [ "$KUBE_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

echo "$KUBE_MACHINE"
