#!/usr/bin/env bash
# Summary: Create a new minikube machine

set -e
[ -n "$KUBE_DEBUG" ] && set -x

KUBE_MACHINE="$1"

if [ -z "$KUBE_MACHINE" ]; then
  KUBE_MACHINE="$(kube-machine-name)"
fi

if [ -z "$KUBE_MACHINE" ] || [ "$KUBE_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

machine_active() {
  local status="$(minikube status --format '{{.MinikubeStatus}}')"
  [ "Running" == "${status}" ]
}

if machine_active "$KUBE_MACHINE"; then
    echo "kube: activate \`$KUBE_MACHINE' already active" >&2
    exit 0
else
    if kube-start "$KUBE_MACHINE"; then
        minikube profile "$KUBE_MACHINE"
        eval "$(minikube docker-env)"
        echo "kube: activate \`$KUBE_MACHINE' activated" >&2
        exit 0
    else
        echo "kube: activate \`$KUBE_MACHINE' not activated" >&2
        exit 1
    fi
fi