#!/usr/bin/env bash
# Summary: Start the minikube machine by name

set -e
[ -n "$KUBE_DEBUG" ] && set -x

if [ -z "$KUBE_MACHINE" ]; then
  KUBE_MACHINE="$(kube-machine-name)"
fi

if [ -z "$KUBE_MACHINE" ] || [ "$KUBE_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.MinikubeStatus}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_start() {
  local machine="$1"
  minikube --profile ${machine} start
}

if machine_running "$KUBE_MACHINE"; then
    echo "kube: machine \`$KUBE_MACHINE' already running" >&2
    exit 0
else
    if machine_start "$KUBE_MACHINE"; then
        minikube-machine regenerate-certs --force "$KUBE_MACHINE"
        echo "kube: machine \`$KUBE_MACHINE' started" >&2
        exit 0
    else
        echo "kube: machine \`$KUBE_MACHINE' is not started" >&2
        exit 1
    fi
fi