#!/usr/bin/env bash
# Summary: Create a new minikube machine

set -e
[ -n "$KUBE_DEBUG" ] && set -x

KUBE_MACHINE="$1"

if [ -z "$KUBE_MACHINE" ]; then
  KUBE_MACHINE="$(kube-machine-name)"
fi

if [ -z "$KUBE_MACHINE" ] || [ "$KUBE_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.Host}}" 2>&1)"
  [ "${running}" == "Running" ]
}

if machine_running "$KUBE_MACHINE"; then
    echo "minikube profile ${KUBE_MACHINE}"
    minikube --profile "${KUBE_MACHINE}" docker-env
    echo "kube: activate \`$KUBE_MACHINE' activated" >&2
    exit 0
else
    echo "kube: activate \`$KUBE_MACHINE' not activated" >&2
    exit 1
fi
