#!/usr/bin/env bash
# Summary: Stop the minikube machine by name

set -e
[ -n "$KUBE_DEBUG" ] && set -x

if [ -z "$KUBE_MACHINE" ]; then
  KUBE_MACHINE="$(kube-machine-name)"
fi

if [ -z "$KUBE_MACHINE" ] || [ "$KUBE_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_stopped() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.MinikubeStatus}}" 2>&1)"
  [ "${running}" == "Stopped" ]
}

machine_stop() {
  local machine="$1"
  minikube --profile ${machine} stop
}

if machine_stopped "$KUBE_MACHINE"; then
    echo "kube: machine \`$KUBE_MACHINE' not running" >&2
    exit 0
else
    if machine_stop "$KUBE_MACHINE"; then
        echo "kube: machine \`$KUBE_MACHINE' stopped" >&2
        exit 0
    else
        echo "kube: machine \`$KUBE_MACHINE' not stopped" >&2
        exit 1
    fi
fi