#!/usr/bin/env bash
# Summary: Create a new minikube machine

set -e
[ -n "$KUBE_DEBUG" ] && set -x

KUBE_MACHINE="$1"

if [ -z "$KUBE_MACHINE" ]; then
  KUBE_MACHINE="$(kube-machine-name)"
fi

if [ -z "$KUBE_MACHINE" ] || [ "$KUBE_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

machine_stopped() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.MinikubeStatus}}" 2>&1)"
  [ "${running}" == "Stopped" ]
}

machine_running() {
  local machine="$1"
  local running="$(minikube --profile ${machine} status --format "{{.MinikubeStatus}}" 2>&1)"
  [ "${running}" == "Running" ]
}

machine_create() {
  local machine="$1"
  minikube start \
      --bootstrapper=kubeadm \
      --vm-driver=virtualbox \
      --memory 8192 \
      --cpus 4 \
      --profile ${machine} \
      2>&1
}

if machine_running "$KUBE_MACHINE"; then
    echo "kube: create \`$KUBE_MACHINE' already running" >&2
    exit 0
elif machine_stopped "$KUBE_MACHINE"; then
    echo "kube: create \`$KUBE_MACHINE' already exists" >&2
    exit 0
else
    if machine_create "$KUBE_MACHINE"; then
        $(kube-machine-file-write .kube-machine "$KUBE_MACHINE")
        echo "kube: create \`$KUBE_MACHINE' created" >&2
        exit 0
    else
        echo "kube: create \`$KUBE_MACHINE' not created" >&2
        exit 1
    fi
fi