#!/usr/bin/env bash

set -e
[ -n "$KUBE_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${KUBE_ROOT}" ]; then
  KUBE_ROOT="${HOME}/.kube"
else
  KUBE_ROOT="${KUBE_ROOT%/}"
fi
export KUBE_ROOT

if [ -z "${KUBE_DIR}" ]; then
  KUBE_DIR="$(pwd)"
else
  cd "$KUBE_DIR" 2>/dev/null || {
    echo "kube: cannot change working directory to \`$KUBE_DIR'"
    exit 1
  } >&2
  KUBE_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export KUBE_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${KUBE_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${KUBE_HOOK_PATH}:${KUBE_ROOT}/kube.d:/usr/local/etc/kube.d:/etc/kube.d:/usr/lib/kube/hooks"
for plugin_hook in "${KUBE_ROOT}/plugins/"*/etc/kube.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export KUBE_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(kube---version)\n$(kube-help)" >&2
  ;;
"-v" )
  exec kube---version
  ;;
* )
  command_path="$(command -v "kube-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "kube: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
